#!/usr/bin/env bash
# instal Nginx and configure it
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index.html
sudo sed -i '/root \/var\/www\/html;/a \    rewrite ^\/redirect_me https:\/\/www.alxafrica.com\/ permanent;' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
st="error_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "/root \/var\/www\/html;/a $st" /etc/nginx/sites-available/default
sudo service nginx restart
